### ISSUE TITLE
Upstream into jenkins job builder

### ISSUE THREAD

**Issue by lynxis** [ettoreleandrotognoli/jjb-discord#1]
Hi,

thank you for the discord integration into jenkins job builder.
Can you upstream it into jenkins-job-builder repository?
See https://jenkins-job-builder.readthedocs.io/en/latest/index.html#writing-a-patch
If you like I could also try to do it.

Thanks,
lynxis

**Comment by ettoreleandrotognoli** [comment]
Hello,

Sure, I'm taking a look on how to do it

**Comment by ettoreleandrotognoli** [comment]
🤞
https://review.opendev.org/c/jjb/jenkins-job-builder/+/878944
